### ISSUE TITLE
threshold : convert image in black/white

### ISSUE THREAD

**Issue by fredmo** [Haidar0096/image_magick_ffi#3]
Hello,

I don't know if this plugin will be long-term support. I hope so.

Is it possible to do a convert in black and white?
In the same way as this linux command :
    convert  IMG_0742.JPG -threshold 37% test37.jpg

Regards,
Frédéric

**Comment by Haidar0096** [comment]
Hello @fredmo.

I am actively working on the plugin and more bindings are coming.

I think what you are looking for is `magickChannelFxImage`, which extracts colors from an image, something like this:

```
      var resultWand = await _wand.magickChannelFxImage("red; green");
      await resultWand?.magickWriteImage('some/directory/grey_image.png');
```

Let me know if this solves your problem.

And always remember that this plugin is to provide bindings to the `MagickWand`  api, so in general all the C functions available there will be available here.

**Comment by Haidar0096** [comment]
The command `magickThresholdImage ` has been implemented in the new packages, so closing this now.
